{
 "title": "prediction accidentologie",
 "description": "dashboard de l'application d'accidentologie ",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Réseau émis conteneurs projet (MB/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (name) (\n  rate(container_network_transmit_bytes_total{name=~\"/?alternance-cicdprediction-.*\"}[5m])\n) / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mémoire utilisée par conteneur (MB)",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (name) (\n  container_memory_usage_bytes{name=~\"/?alternance-cicdprediction-.*\"}\n) / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Réseau reçu par conteneur (MB/s)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (name) (\n  rate(container_network_receive_bytes_total{name=~\"/?alternance-cicdprediction-.*\"}[5m])\n) / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[30s])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU par conteneur (%)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum by (name) (\n  rate(container_cpu_usage_seconds_total{name=~\"/?alternance-cicdprediction-.*\"}[5m])\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk usage %",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (\n  1 - (\n    node_filesystem_avail_bytes{fstype!~\"tmpfs|overlay\",mountpoint=\"/\"}\n    /\n    node_filesystem_size_bytes{fstype!~\"tmpfs|overlay\",mountpoint=\"/\"}\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage %",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "taux d'erreur %",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * sum (rate(prediction_http_errors_total[5m])) / sum(rate(prediction_requests_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latence P95 actuelle",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 6, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(prediction_request_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime application minutes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "app_uptime_seconds / 60", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Résultats par classe",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "prediction_results_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total erreurs HTTP",
   "type": "table",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 37 },
   "targets": [
    { "expr": "prediction_http_errors_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "total erreur de validation",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prediction_validation_errors_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total requetes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "prediction_requests_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Latence moyenne",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "targets": [
    {
     "expr": "rate(prediction_request_duration_seconds_sum[1m])\n/\nrate(prediction_request_duration_seconds_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Erreurs de validation / min",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "rate(prediction_http_errors_total[1m])*60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "requete/min",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 52 },
   "targets": [
    {
     "expr": "rate(prediction_requests_total[1m]) * 60",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}